rule all:
    input:
        # Representative
        ["0_minimiser_hash_20_"+str(w)+"_distance_"+str(error)+".out" for w in range(24,44,4) for error in [1,2,5,10]],
        ["0_modmer_hash_20_"+str(w)+"_distance_"+str(error)+".out" for w in [3,5,7,9,11] for error in [1,2,5,10]],
        ["syncmer_hash_20_"+str(w)+"_0_0_distance_"+str(error)+".out" for w in [18,16,14,12,10] for error in [1,2,5,10]],
        ["syncmer_hash_20_"+str(w)+"_0_6_distance_"+str(error)+".out" for w in [15,11,7,3,1] for error in [1,2,5,10]],
        # Representative based on strobemers
        ["hybridstrobemers_2_"+str(0)+"_"+str(4+k)+"_minimiser_hash_10_"+str(w)+"_distance_"+str(error)+".out" for k in [10] for w in range(24,44,4) for error in [1,2,5,10]],
        ["minstrobemers_2_"+str(0)+"_"+str(3+k)+"_minimiser_hash_10_"+str(w)+"_distance_"+str(error)+".out" for k in [10] for w in range(24,44,4) for error in [1,2,5,10]],
        ["randstrobemers_2_"+str(0)+"_"+str(3+k)+"_minimiser_hash_10_"+str(w)+"_distance_"+str(error)+".out" for k in [10] for w in range(24,44,4) for error in [1,2,5,10]],
        ["hybridstrobemers_2_"+str(0)+"_"+str(7+k)+"_minimiser_hash_10_"+str(w)+"_distance_"+str(error)+".out" for k in [10] for w in range(24,44,4) for error in [1,2,5,10]],
        ["minstrobemers_2_"+str(0)+"_"+str(7+k)+"_minimiser_hash_10_"+str(w)+"_distance_"+str(error)+".out" for k in [10] for w in range(24,44,4) for error in [1,2,5,10]],
        ["randstrobemers_2_"+str(0)+"_"+str(7+k)+"_minimiser_hash_10_"+str(w)+"_distance_"+str(error)+".out" for k in [10] for w in range(24,44,4) for error in [1,2,5,10]]

rule download_human_genome:
    output:
        "../results/GRCh38.p13.genome.fa.gz"
    shell:
        """wget "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/GRCh38.p13.genome.fa.gz"  -O "../results/GRCh38.p13.genome.fa.gz" """

rule distance_minimiser_modmer:
    input:
        "../results/GRCh38.p13.genome.fa.gz"
    output:
        "{shape}_{method}_hash_{kmer_size}_{w_size}_distance_{error}.out"
    wildcard_constraints:
         shape='[0-9]*',
         method='(modmer|minimiser)'
    shell:
        "minions distance --method {wildcards.method} -k {wildcards.kmer_size} -w {wildcards.w_size} --shape {wildcards.shape} -o {wildcards.shape}_  {input} > {wildcards.shape}_{wildcards.method}_hash_{wildcards.kmer_size}_{wildcards.w_size}_distance_{wildcards.error}.out"

rule distance_syncmer:
    input:
        "../results/GRCh38.p13.genome.fa.gz"
    output:
        "syncmer_hash_{kmer_size}_{w_size}_{pos_begin}_{pos_end}_distance_{error}.out",
    shell:
        "minions distance --method syncmer -k {wildcards.kmer_size} -w {wildcards.w_size} -p {wildcards.pos_begin} -p {wildcards.pos_end} --shape 0 {input} > syncmer_hash_{wildcards.kmer_size}_{wildcards.w_size}_{wildcards.pos_begin}_{wildcards.pos_end}_distance_{wildcards.error}.out"

rule distance_strobemer:
    input:
        "../results/GRCh38.p13.genome.fa.gz"
    output:
        "{method}strobemers_{kmer_size}_{order}_{wmin}_{wmax}_distance_{error}.out"
    wildcard_constraints:
         method='(min|rand|hybrid)',
         kmer_size='[0-9]*',
         order='(2|3)',
         wmin='[0-9]*',
         wmax='[0-9]*'
    shell:
        "minions distance --method strobemer --{wildcards.method} -k {wildcards.kmer_size} --w-min {wildcards.wmin} --w-max {wildcards.wmax} --order {wildcards.order} {input} > {wildcards.method}strobemers_{wildcards.kmer_size}_{wildcards.order}_{wildcards.wmin}_{wildcards.wmax}_distance_{wildcards.error}.out"

rule distance_minimiser_modmer_strobemer:
    input:
        "../results/GRCh38.p13.genome.fa.gz"
    output:
        "{method2}strobemers_{order}_{wmin}_{wmax}_{method}_hash_{kmer_size}_{w_size}_distance_{error}.out"
    wildcard_constraints:
         method='(modmer|minimiser)',
         method2='(min|rand|hybrid)',
         order='(2|3)',
         kmer_size='[0-9]*',
         w_size='[0-9]*',
         wmin='[0-9]*',
         wmax='[0-9]*'
    shell:
        "minions distance --method {wildcards.method} -k {wildcards.kmer_size} -w {wildcards.w_size} --strobemer --w-min {wildcards.wmin} --w-max {wildcards.wmax} --{wildcards.method2} --order {wildcards.order} {input} > {wildcards.method2}strobemers_{wildcards.order}_{wildcards.wmin}_{wildcards.wmax}_{wildcards.method}_hash_{wildcards.kmer_size}_{wildcards.w_size}_distance_{wildcards.error}.out"
