// -----------------------------------------------------------------------------------------------------
// Copyright (c) 2006-2021, Knut Reinert & Freie Universität Berlin
// Copyright (c) 2016-2021, Knut Reinert & MPI für molekulare Genetik
// This file may be used, modified and/or redistributed under the terms of the 3-clause BSD-License
// shipped with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE.md
// -----------------------------------------------------------------------------------------------------

/*!\file
 * \author Hossein Eizadi Moghadam <hosseinem AT fu-berlin.de>
 * \brief Provides minstrobe.
 */

#pragma once

#include <seqan3/std/algorithm>
#include <deque>
#include <tuple>

#include <seqan3/core/detail/empty_type.hpp>
#include <seqan3/core/range/detail/adaptor_from_functor.hpp>
#include <seqan3/core/range/type_traits.hpp>
#include <seqan3/utility/range/concept.hpp>
#include <seqan3/utility/type_traits/lazy_conditional.hpp>

namespace seqan3::detail
{
// ---------------------------------------------------------------------------------------------------------------------
// minstrobe_view class
// ---------------------------------------------------------------------------------------------------------------------

/*!\brief The type returned by minstrobe.
 * \tparam urng1_t The type of the underlying range, must model std::ranges::forward_range, the reference type must
 *                 model std::totally_ordered. The typical use case is that the reference type is the result of
 *                 seqan3::kmer_hash.
 * \implements std::ranges::view
 * \ingroup search_views
 *
 *
 * \note Most members of this class are generated by std::ranges::view_interface which is not yet documented here.

 */
template <std::ranges::view urng1_t>
class minstrobe_view : public std::ranges::view_interface<minstrobe_view<urng1_t>>
{
private:
    static_assert(std::ranges::forward_range<urng1_t>, "The minstrobe_view only works on forward_ranges.");
    static_assert(std::totally_ordered<std::ranges::range_reference_t<urng1_t>>,
                  "The reference type of the underlying range must model std::totally_ordered.");

    //!\brief Whether the given ranges are const_iterable.
    static constexpr bool const_iterable = seqan3::const_iterable_range<urng1_t>;

    //!\brief The first underlying range.
    urng1_t urange1{};

    //!\brief lower offset for the position of the next window.
    size_t window_min{};

    //!\brief upper offset for the position of the next window.
    size_t window_max{};

    template <bool const_range>
    class basic_iterator;

    //!\brief The sentinel type of the minstrobe_view.
    using sentinel = std::default_sentinel_t;

public:
    /*!\name Constructors, destructor and assignment
     * \{
     */
     /// \cond Workaround_Doxygen
    minstrobe_view() requires std::default_initializable<urng1_t> = default; //!< Defaulted.
    /// \endcond
    minstrobe_view(minstrobe_view const & rhs) = default; //!< Defaulted.
    minstrobe_view(minstrobe_view && rhs) = default; //!< Defaulted.
    minstrobe_view & operator=(minstrobe_view const & rhs) = default; //!< Defaulted.
    minstrobe_view & operator=(minstrobe_view && rhs) = default; //!< Defaulted.
    ~minstrobe_view() = default; //!< Defaulted.

    /*!\brief Construct from a view and a given number of values in one window.
    * \param[in] urange1     The input range to process. Must model std::ranges::viewable_range and
    *                        std::ranges::forward_range.
    * \param[in] window_min  The lower offset for the position of the next window from the previous one.
    * \param[in] window_max  The upper offset for the position of the next window from the previous one.
    */
    minstrobe_view(urng1_t urange1, size_t const window_min, size_t const window_max) :
        urange1{std::move(urange1)},
        window_min{window_min},
        window_max{window_max}
    {}

    /*!\brief Construct from a non-view that can be view-wrapped and a given number of values in one window.
    * \tparam other_urng1_t  The type of another urange. Must model std::ranges::viewable_range and be constructible
                             from urng1_t.
    * \param[in] urange1     The input range to process. Must model std::ranges::viewable_range and
    *                        std::ranges::forward_range.
    * \param[in] window_min  The lower offset for the position of the next window from the previous one.
    * \param[in] window_max  The upper offset for the position of the next window from the previous one.
    */
    template <typename other_urng1_t>
    //!\cond
        requires (std::ranges::viewable_range<other_urng1_t> &&
                  std::constructible_from<urng1_t, ranges::ref_view<std::remove_reference_t<other_urng1_t>>>)
    //!\endcond
    minstrobe_view(other_urng1_t && urange1, size_t const window_min, size_t const window_max) :
        urange1{std::views::all(std::forward<other_urng1_t>(urange1))},
        window_min{window_min},
        window_max{window_max}
    {}

    /*!\name Iterators
     * \{
     */
    /*!\brief Returns an iterator to the first element of the range.
     * \returns Iterator to the first element.
     *
     * \details
     *
     * ### Complexity
     *
     * Constant.
     *
     * ### Exceptions
     *
     * Strong exception guarantee.
     */
    basic_iterator<false> begin()
    {
        return {std::ranges::begin(urange1),
                std::ranges::end(urange1),
                window_min,
                window_max};
    }

    //!\copydoc begin()
    basic_iterator<true> begin() const
    //!\cond
        requires const_iterable
    //!\endcond
    {
        return {std::ranges::cbegin(urange1),
                std::ranges::cend(urange1),
                window_min,
                window_max};
    }

    /*!\brief Returns an iterator to the element following the last element of the range.
     * \returns Iterator to the end.
     *
     * \details
     *
     * This element acts as a placeholder; attempting to dereference it results in undefined behaviour.
     *
     * ### Complexity
     *
     * Constant.
     *
     * ### Exceptions
     *
     * No-throw guarantee.
     */
    sentinel end() const
    {
        return {};
    }
    //!\}
};

//!\brief Iterator for calculating minstrobes.
template <std::ranges::view urng1_t>
template <bool const_range>
class minstrobe_view<urng1_t>::basic_iterator
{
private:
    //!\brief The sentinel type of the first underlying range.
    using urng1_sentinel_t = maybe_const_sentinel_t<const_range, urng1_t>;
    //!\brief The iterator type of the first underlying range.
    using urng1_iterator_t = maybe_const_iterator_t<const_range, urng1_t>;

    template <bool>
    friend class basic_iterator;

public:
    /*!\name Associated types
     * \{
     */
    //!\brief Type for distances between iterators.
    using difference_type = std::ranges::range_difference_t<urng1_t>;
    //!\brief Value type of this iterator.
    using value_t = std::ranges::range_value_t<urng1_t>;
    //!\brief Value type of the output.
    using value_type = std::tuple<value_t, value_t>;
    //!\brief The pointer type.
    using pointer = void;
    //!\brief Reference to `value_type`.
    using reference = value_type;
    //!\brief Tag this class as a forward iterator.
    using iterator_category = std::forward_iterator_tag;
    //!\brief Tag this class as a forward iterator.
    using iterator_concept = iterator_category;
    //!\}

    /*!\name Constructors, destructor and assignment
     * \{
     */
    basic_iterator() = default; //!< Defaulted.
    basic_iterator(basic_iterator const &) = default; //!< Defaulted.
    basic_iterator(basic_iterator &&) = default; //!< Defaulted.
    basic_iterator & operator=(basic_iterator const &) = default; //!< Defaulted.
    basic_iterator & operator=(basic_iterator &&) = default; //!< Defaulted.
    ~basic_iterator() = default; //!< Defaulted.

    //!\brief Allow iterator on a const range to be constructible from an iterator over a non-const range.
    basic_iterator(basic_iterator<!const_range> const & it)
    //!\cond
        requires const_range
    //!\endcond
        : minstrobe_value{std::move(it.minstrobe_value)},
          urng1_iterator{std::move(it.urng1_iterator)},
          urng1_sentinel{std::move(it.urng1_sentinel)}

    {}

    /*!\brief Construct from begin and end iterators of a given range over std::totally_ordered values, and the number
              of values per window.
    * \param[in] urng1_iterator Iterator pointing to the first position of the first std::totally_ordered range.
    * \param[in] urng1_sentinel Iterator pointing to the last position of the first std::totally_ordered range.
    * \param[in] window_min  The lower offset for the position of the next window from the previous one.
    * \param[in] window_max  The upper offset for the position of the next window from the previous one.
    *
    * \details
    *
    * Looks at the number of values per window with two iterators. First iterator adds the next value in the tuple as
    * the first strobe. The second iterator adds the minimum value of the window to the second position of the tuple.
    *
    */
    basic_iterator(urng1_iterator_t urng1_iterator,
                   urng1_sentinel_t urng1_sentinel,
                   size_t window_min,
                   size_t window_max) :
        urng1_iterator{std::move(urng1_iterator)},
        urng1_sentinel{std::move(urng1_sentinel)}
    {
        window_first(window_min, window_max);
    }
    //!\}

    //!\anchor basic_iterator_comparison_minstrobe
    //!\name Comparison operators
    //!\{

    //!\brief Compare to another basic_iterator.
    friend bool operator==(basic_iterator const & lhs, basic_iterator const & rhs)
    {
        return (lhs.urng1_iterator == rhs.urng1_iterator);
    }

    //!\brief Compare to another basic_iterator.
    friend bool operator!=(basic_iterator const & lhs, basic_iterator const & rhs)
    {
        return !(lhs == rhs);
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator==(basic_iterator const & lhs, sentinel const &)
    {
        return lhs.urng1_iterator == lhs.urng1_sentinel;
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator==(sentinel const & lhs, basic_iterator const & rhs)
    {
        return rhs == lhs;
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator!=(sentinel const & lhs, basic_iterator const & rhs)
    {
        return !(lhs == rhs);
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator!=(basic_iterator const & lhs, sentinel const & rhs)
    {
        return !(lhs == rhs);
    }
    //!\}

    //!\brief Pre-increment.
    basic_iterator & operator++() noexcept
    {
        next_unique_minstrobe();
        return *this;
    }

    //!\brief Post-increment.
    basic_iterator operator++(int) noexcept
    {
        basic_iterator tmp{*this};
        next_unique_minstrobe();
        return tmp;
    }

    //!\brief Return the minstrobe.
    value_type operator*() const noexcept
    {
        return minstrobe_value;
    }

private:
    //!\brief The minstrobe value.
    value_type minstrobe_value{};

    //!\brief The offset relative to the beginning of the window where the minstrobe value is found.
    size_t minstrobe_position_offset{};

    //!\brief Iterator to the right most value of the window.
    urng1_iterator_t urng1_iterator{};
    //!\brief Iterator to the first value of minstrobe.
    urng1_iterator_t first_iterator{};
    //!\brief Iterator to last element in range.
    urng1_sentinel_t urng1_sentinel{};

    //!\brief Stored values per window. It is necessary to store them, because a shift can remove the current minstrobe.
    std::deque<value_t> window_values{};

    //!\brief The number of values in one window.
    size_t window_size{};

    //!\brief Increments iterator by 1.
    void next_unique_minstrobe()
    {
        while (!next_minstrobe()) {}
    }

    //!\brief Returns new window value of the first iterator.
    auto window_value() const
    {
        return *urng1_iterator;
    }

    //!\brief Returns new window value of the first iterator.
    auto first_window_value() const
    {
        return *first_iterator;
    }

    //!\brief Advances the window of the first iterator to the next position.
    void advance_window()
    {
        ++urng1_iterator;
    }

    //!\brief Advances the window of the first iterator to the next position.
    void advance_all_windows()
    {
        ++first_iterator;
	++urng1_iterator;
    }

    //!\brief Calculates minstrobes for the first window.
    void window_first(const size_t window_min, const size_t window_max)
    {
	window_size = (window_max - window_min + 1);

	if (window_size == 0u)
            return;

	first_iterator = urng1_iterator;
	std::advance(urng1_iterator, window_min);

        for (int i = 1u; i < window_size; ++i)
        {
            window_values.push_back(window_value());
            advance_window();
        }
        window_values.push_back(window_value());

        auto minstrobe_it = std::ranges::min_element(window_values, std::less_equal<value_t>{});
        minstrobe_value = std::make_tuple(first_window_value(), *minstrobe_it);
        minstrobe_position_offset = std::distance(std::begin(window_values), minstrobe_it);

    }

    /*!\brief Calculates the next minstrobe value.
     * \returns True, if new minstrobe is found or end is reached. Otherwise returns false.
     * \details
     * For the following windows, we remove the first window value (is now not in window_values) and add the new
     * value that results from the window shifting.
     */
    bool next_minstrobe()
    {
    	advance_all_windows();

        if (urng1_iterator == urng1_sentinel)
            return true;

        value_t const new_value = first_window_value();
        value_t const sw_new_value = window_value();


        std::get<0>(minstrobe_value) = new_value;

        window_values.pop_front();
        window_values.push_back(sw_new_value);

	if (minstrobe_position_offset == 0)
	{
		auto minstrobe_it = std::ranges::min_element(window_values, std::less_equal<value_t>{});
		std::get<1>(minstrobe_value) = *minstrobe_it;
		minstrobe_position_offset = std::distance(std::begin(window_values), minstrobe_it);
		return true;

	}

	if (sw_new_value < std::get<1>(minstrobe_value))
	     {
	          std::get<1>(minstrobe_value) = sw_new_value;
	          minstrobe_position_offset = window_values.size() - 1;
	          return true;
	     }

	--minstrobe_position_offset;
	return true;
    }
};



//!\brief A deduction guide for the view class template.
template <std::ranges::viewable_range rng1_t>
minstrobe_view(rng1_t &&, size_t const window_min, size_t const window_max) -> minstrobe_view<std::views::all_t<rng1_t>>;



// ---------------------------------------------------------------------------------------------------------------------
// minstrobe_fn (adaptor definition)
// ---------------------------------------------------------------------------------------------------------------------

//![adaptor_def]
//!\brief minstrobe's range adaptor object type (non-closure).
//!\ingroup search_views
struct minstrobe_fn
{
    //!\brief Store the number of values in two windows and return a range adaptor closure object.
    constexpr auto operator()(const size_t window_min, const size_t window_max) const
    {
        return adaptor_from_functor{*this, window_min, window_max};
    }

    /*!\brief Call the view's constructor with two arguments: the underlying view and an integer indicating how many
     *        values one window contains.
     * \tparam urng1_t        The type of the input range to process. Must model std::ranges::viewable_range.
     * \param[in] urange1     The input range to process. Must model std::ranges::viewable_range and
     *                        std::ranges::forward_range.
     * \param[in] window_min  The lower offset for the position of the next window from the previous one.
     * \param[in] window_max  The upper offset for the position of the next window from the previous one.
     * \returns  A range of converted values in tuples.
     */
    template <std::ranges::range urng1_t>
    constexpr auto operator()(urng1_t && urange1, size_t const window_min, size_t const window_max) const
    {
        static_assert(std::ranges::viewable_range<urng1_t>,
                      "The range parameter to views::minstrobe cannot be a temporary of a non-view range.");
        static_assert(std::ranges::forward_range<urng1_t>,
                      "The range parameter to views::minstrobe must model std::ranges::forward_range.");

        if (window_max - window_min == 0) // Would just return urange1 without any changes
            throw std::invalid_argument{"The chosen min and max windows are not valid. "
                                        "Please choose a value greater than 1 or use two ranges."};

        return minstrobe_view{urange1, window_min, window_max};
    }
};
//![adaptor_def]

} // namespace seqan3::detail

namespace seqan3::views
{
/*!\brief Computes minstrobes for a range of comparable values. A minstrobe is a value that is composed of a few single strobes concatenated together, chosen window_min elements apart based on their minimum value in a window.
 * \tparam urng_t The type of the first range being processed. See below for requirements. [template
 *                 parameter is omitted in pipe notation]
 * \param[in] urange1 The range being processed. [parameter is omitted in pipe notation]
 * \param[in] window_min  The lower offset for the position of the next window from the previous one.
 * \param[in] window_max  The upper offset for the position of the next window from the previous one.
 * \returns A range of std::totally_ordered where each value is ... See below for the
 *          properties of the returned range.
 * \ingroup search_views
 *
 *
 * ### View properties
 *
 * | Concepts and traits              | `urng_t` (underlying range type)   | `rrng_t` (returned range type)   |
 * |----------------------------------|:----------------------------------:|:--------------------------------:|
 * | std::ranges::input_range         | *required*                         | *preserved*                      |
 * | std::ranges::forward_range       | *required*                         | *preserved*                      |
 * | std::ranges::bidirectional_range |                                    | *lost*                           |
 * | std::ranges::random_access_range |                                    | *lost*                           |
 * | std::ranges::contiguous_range    |                                    | *lost*                           |
 * |                                  |                                    |                                  |
 * | std::ranges::viewable_range      | *required*                         | *guaranteed*                     |
 * | std::ranges::view                |                                    | *guaranteed*                     |
 * | std::ranges::sized_range         |                                    | *lost*                           |
 * | std::ranges::common_range        |                                    | *lost*                           |
 * | std::ranges::output_range        |                                    | *lost*                           |
 * | seqan3::const_iterable_range     |                                    | *preserved*                      |
 * |                                  |                                    |                                  |
 * | std::ranges::range_reference_t   | std::totally_ordered               | std::totally_ordered             |
 *
 * See the views views submodule documentation for detailed descriptions of the view properties.
 */
inline constexpr auto minstrobe = detail::minstrobe_fn{};

} // namespace seqan3::views
