// -----------------------------------------------------------------------------------------------------
// Copyright (c) 2006-2021, Knut Reinert & Freie Universität Berlin
// Copyright (c) 2016-2021, Knut Reinert & MPI für molekulare Genetik
// This file may be used, modified and/or redistributed under the terms of the 3-clause BSD-License
// shipped with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE.md
// -----------------------------------------------------------------------------------------------------

/*!\file
 * \author Hossein Eizadi Moghadam <hosseinem AT fu-berlin.de> & Mitra Darvish <mitra darvish AT fu-berlin.de>
 * \brief Provides minstrobe.
 */

#pragma once

#include <seqan3/std/algorithm>
#include <deque>

#include <seqan3/core/detail/empty_type.hpp>
#include <seqan3/core/range/detail/adaptor_from_functor.hpp>
#include <seqan3/core/range/type_traits.hpp>
#include <seqan3/utility/range/concept.hpp>
#include <seqan3/utility/type_traits/lazy_conditional.hpp>

namespace seqan3::detail
{
// ---------------------------------------------------------------------------------------------------------------------
// minstrobe_view class
// ---------------------------------------------------------------------------------------------------------------------

/*!\brief The type returned by minstrobe.
 * \tparam urng_t The type of the underlying range, must model std::ranges::forward_range, the reference type must
 *                 model std::totally_ordered. The typical use case is that the reference type is the result of
 *                 seqan3::kmer_hash.
 * \tparam order  The order of strobemers, at the moment the order 2 and 3 are supported. Default is 2.
 * \implements std::ranges::view
 * \ingroup search_views
 *
 *
 * \note Most members of this class are generated by std::ranges::view_interface which is not yet documented here.
 */
template <std::ranges::view urng_t, std::uint16_t order = 2>
class minstrobe_view : public std::ranges::view_interface<minstrobe_view<urng_t>>
{
private:
    static_assert(std::ranges::forward_range<urng_t>, "The minstrobe_view only works on forward_ranges.");
    static_assert(std::totally_ordered<std::ranges::range_reference_t<urng_t>>,
                  "The reference type of the underlying range must model std::totally_ordered.");

    //!\brief Whether the given ranges are const_iterable.
    static constexpr bool const_iterable = seqan3::const_iterable_range<urng_t>;

    //!\brief Whether the given order is of range 3.
    static constexpr bool order_3 = (order == 3);

    //!\brief The underlying range.
    urng_t urange{};

    //!\brief The distance of the second strobe to the first one.
    size_t window_dist{};

    //!\brief The number of elements in a window.
    size_t window_size{};

    template <bool const_range>
    class basic_iterator;

    //!\brief The sentinel type of the minstrobe_view.
    using sentinel = std::default_sentinel_t;

public:
    /*!\name Constructors, destructor and assignment
     * \{
     */
     /// \cond Workaround_Doxygen
    minstrobe_view() requires std::default_initializable<urng_t> = default; //!< Defaulted.
    /// \endcond
    minstrobe_view(minstrobe_view const & rhs) = default; //!< Defaulted.
    minstrobe_view(minstrobe_view && rhs) = default; //!< Defaulted.
    minstrobe_view & operator=(minstrobe_view const & rhs) = default; //!< Defaulted.
    minstrobe_view & operator=(minstrobe_view && rhs) = default; //!< Defaulted.
    ~minstrobe_view() = default; //!< Defaulted.

    /*!\brief Construct from a view and the two (lower and upper) offsets of the second window.
    * \param[in] urange      The input range to process. Must model std::ranges::viewable_range and
    *                        std::ranges::forward_range.
    * \param[in] window_dist The distance of the second strobe to the first one.
    * \param[in] window_size The number of elements in a window.
    */
    minstrobe_view(urng_t urange, size_t const window_dist, size_t const window_size) :
        urange{std::move(urange)},
        window_dist{window_dist},
        window_size{window_size}
    {}

    /*!\brief Construct from a non-view that can be view-wrapped and the two (lower and upper) offsets
    *        of the second window.
    * \tparam other_urng_t   The type of another urange. Must model std::ranges::viewable_range and be
                             constructible from urng_t.
    * \param[in] urange      The input range to process. Must model std::ranges::viewable_range and
    *                        std::ranges::forward_range.
    * \param[in] window_dist The distance of the second strobe to the first one.
    * \param[in] window_size The number of elements in a window.
    */
    template <typename other_urng_t>
    //!\cond
        requires (std::ranges::viewable_range<other_urng_t> &&
                  std::constructible_from<urng_t, ranges::ref_view<std::remove_reference_t<other_urng_t>>>)
    //!\endcond
    minstrobe_view(other_urng_t && urange, size_t const window_dist, size_t const window_size) :
        urange{std::views::all(std::forward<other_urng_t>(urange))},
        window_dist{window_dist},
        window_size{window_size}
    {}

    /*!\name Iterators
     * \{
     */
    /*!\brief Returns an iterator to the first element of the range.
     * \returns Iterator to the first element.
     *
     * \details
     *
     * ### Complexity
     *
     * Constant.
     *
     * ### Exceptions
     *
     * Strong exception guarantee.
     */
    basic_iterator<false> begin()
    {
        return {std::ranges::begin(urange),
                std::ranges::begin(urange),
                std::ranges::end(urange),
                window_dist,
                window_size};
    }

    //!\copydoc begin()
    basic_iterator<true> begin() const
    //!\cond
        requires const_iterable
    //!\endcond
    {
        return {std::ranges::cbegin(urange),
                std::ranges::cbegin(urange),
                std::ranges::cend(urange),
                window_dist,
                window_size};
    }

    /*!\brief Returns an iterator to the element following the last element of the range.
     * \returns Iterator to the end.
     * ### Complexity
     *
     * Constant.
     * \details
     *
     * This element acts as a placeholder; attempting to dereference it results in undefined behaviour.
     *
     * ### Exceptions
     *
     * No-throw guarantee.
     */
    sentinel end() const
    {
        return{};
    }
    //!\}
};

//!\brief Iterator for calculating minstrobes.
template <std::ranges::view urng_t, std::uint16_t order>
template <bool const_range>
class minstrobe_view<urng_t, order>::basic_iterator
{
private:
    //!\brief The sentinel type of the underlying range.
    using urng_sentinel_t = maybe_const_sentinel_t<const_range, urng_t>;
    //!\brief The iterator type of the underlying range.
    using urng_iterator_t = maybe_const_iterator_t<const_range, urng_t>;

    template <bool>
    friend class basic_iterator;

public:
    /*!\name Associated types
     * \{
     */
    //!\brief Type for distances between iterators.
    using difference_type = std::ranges::range_difference_t<urng_t>;
    //!\brief Value type of the iterator.
    using value_t = std::ranges::range_value_t<urng_t>;
    //!\brief Value type of the output.
    using value_type = std::vector<value_t>;
    //!\brief The pointer type.
    using pointer = void;
    //!\brief Reference to `value_type`.
    using reference = value_type;
    //!\brief Tag this class as a forward iterator.
    using iterator_category = std::bidirectional_iterator_tag;
    //!\brief Tag this class as a forward iterator.
    using iterator_concept = iterator_category;
    //!\}

    /*!\name Constructors, destructor and assignment
     * \{
     */
    basic_iterator() = default; //!< Defaulted.
    basic_iterator(basic_iterator const &) = default; //!< Defaulted.
    basic_iterator(basic_iterator &&) = default; //!< Defaulted.
    basic_iterator & operator=(basic_iterator const &) = default; //!< Defaulted.
    basic_iterator & operator=(basic_iterator &&) = default; //!< Defaulted.
    ~basic_iterator() = default; //!< Defaulted.

    //!\brief Allow iterator on a const range to be constructible from an iterator over a non-const range.
    basic_iterator(basic_iterator<!const_range> const & it)
    //!\cond
        requires const_range
    //!\endcond
        : minstrobe_value{std::move(it.minstrobe_value)},
          first_iterator{std::move(it.first_iterator)},
          second_iterator{std::move(it.second_iterator)},
          third_iterator{std::move(it.third_iterator)},
          urng_sentinel{std::move(it.urng_sentinel)}

    {}

    /*!\brief Construct from two begin and one end iterators of a given range over std::totally_ordered values, and the two
    *         (lower and upper) offsets of the second window.
    * \param[in] second_iterator Iterator pointing to the first position of the second window of the std::totally_ordered range.
    * \param[in] third_iterator  Iterator pointing to the first position of the third window of the std::totally_ordered range.
    * \param[in] urng_sentinel   Iterator pointing to the last position of the second window of the std::totally_ordered range.
    * \param[in] window_dist     The distance of the second strobe to the first one.
    * \param[in] window_size     The number of elements in a window.
    *
    * \details
    *
    * Looks at the number of values per two windows with three iterators. First iterator adds the next value in the vector as
    * the first strobe. The second iterator adds the minimum value of the second window to the second position of the vector.
    * The third iterator adds the minimum value of the third window to the third position of the vector.
    *
    */
    basic_iterator(urng_iterator_t second_iterator,
                   urng_iterator_t third_iterator,
                   urng_sentinel_t urng_sentinel,
                   size_t window_dist,
                   size_t window_size) :
        first_iterator{std::move(first_iterator)},
        second_iterator{std::move(second_iterator)},
        third_iterator{std::move(third_iterator)},
        urng_sentinel{std::move(urng_sentinel)}
    {
        size_t size{};
        if constexpr(order_3)
        {
            size = std::ranges::distance(third_iterator, urng_sentinel);
        }
        else
        {
            size = std::ranges::distance(second_iterator, urng_sentinel);
        }

        window_first(window_dist, window_size);
    }

    basic_iterator(urng_iterator_t second_iterator,
                   urng_iterator_t third_iterator,
                   urng_sentinel_t urng_sentinel,
                   size_t window_dist,
                   size_t window_size,
                   bool is_end) :
        first_iterator{std::move(first_iterator)},
        second_iterator{std::move(second_iterator)},
        third_iterator{std::move(third_iterator)},
        urng_sentinel{std::move(urng_sentinel)}
    {
        size_t size{};
        if constexpr(order_3)
        {
            size = std::ranges::distance(third_iterator, urng_sentinel);
        }
        else
        {
            size = std::ranges::distance(second_iterator, urng_sentinel);
        }

        if (is_end)
        {
            auto urange_size = std::ranges::distance(second_iterator, urng_sentinel);
            if constexpr(order_3)
                second_iterator = std::ranges::next(second_iterator, urange_size-(window_size*2)-window_dist, urng_sentinel);
            else
                second_iterator = std::ranges::next(second_iterator, urange_size-window_size-window_dist, urng_sentinel);
        }
        window_first(window_dist, window_size);
    }
    //!\}

    //!\anchor basic_iterator_comparison_minstrobe
    //!\name Comparison operators
    //!\{

    //!\brief Compare to another basic_iterator.
    friend bool operator==(basic_iterator const & lhs, basic_iterator const & rhs)
    {
        return (lhs.first_iterator == rhs.first_iterator) &&
               (lhs.second_iterator == rhs.second_iterator) &&
               (lhs.third_iterator == rhs.third_iterator);
    }

    //!\brief Compare to another basic_iterator.
    friend bool operator!=(basic_iterator const & lhs, basic_iterator const & rhs)
    {
        return !(lhs == rhs);
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator==(basic_iterator const & lhs, sentinel const &)
    {
        if constexpr(order_3)
            return lhs.third_iterator == lhs.urng_sentinel;
        else
            return lhs.second_iterator == lhs.urng_sentinel;
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator==(sentinel const & lhs, basic_iterator const & rhs)
    {
        return rhs == lhs;
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator!=(sentinel const & lhs, basic_iterator const & rhs)
    {
        return !(lhs == rhs);
    }

    //!\brief Compare to the sentinel of the minstrobe_view.
    friend bool operator!=(basic_iterator const & lhs, sentinel const & rhs)
    {
        return !(lhs == rhs);
    }
    //!\}

    //!\brief Pre-increment.
    basic_iterator & operator++() noexcept
    {
        next_minstrobe();
        return *this;
    }

    //!\brief Post-increment.
    basic_iterator operator++(int) noexcept
    {
        basic_iterator tmp{*this};
        next_minstrobe();
        return tmp;
    }

    /*!\brief Pre-decrement.
    * \attention This function is only available if underlying range is bidirectional.
    */
    basic_iterator & operator--() noexcept
        requires std::ranges::bidirectional_range<urng_t>
    {
        prev_minstrobe();
        return *this;
    }

    /*!\brief Post-decrement.
     * \attention This function is only available if underlying range is bidirectional.
     */
    basic_iterator operator--(int) noexcept
        requires std::ranges::bidirectional_range<urng_t>
    {
        basic_iterator tmp{*this};
        prev_minstrobe();
        return tmp;
    }


    //!\brief Return the minstrobe.
    value_type operator*() const noexcept
    {
        return minstrobe_value;
    }

private:
    //!\brief The minstrobe value.
    value_type minstrobe_value{};

    //!\brief The offset relative to the beginning of the window where the minstrobe value is found.
    size_t minstrobe_position_offset{};

    //!\brief The offset relative to the beginning of the window where the minstrobe value is found.
    size_t minstrobe_position_offset3{};

    //!\brief Iterator to the first strobe of minstrobe.
    urng_iterator_t first_iterator{};

    //!\brief Iterator to the right most value of the window and hence the second strobe of minstrobe.
    urng_iterator_t second_iterator{};

    //!\brief Iterator to the right most value of the window and hence the third strobe of minstrobe.
    urng_iterator_t third_iterator{};

    //!\brief Iterator to the left most value of the window and hence the second strobe of minstrobe for bidirectionality.
    urng_iterator_t second_iterator_back{};

    //!\brief Iterator to the left most value of the window and hence the third strobe of minstrobe for bidirectionality.
    urng_iterator_t third_iterator_back{};

    //!\brief Iterator to first element in range.
    urng_sentinel_t urng_first{};

    //!\brief Iterator to last element in range.
    urng_sentinel_t urng_sentinel{};

    //!\brief Stored values per window. It is necessary to store them, because a shift can remove the current minstrobe.
    std::deque<value_t> window_values{};

    //!\brief Stored values per window. It is necessary to store them, because a shift can remove the current minstrobe.
    std::deque<value_t> window_values3{};

    //!\brief Advances the window of the iterators to their next position.
    void advance_windows()
    {
        ++first_iterator;
        ++second_iterator;
        ++second_iterator_back;

        if constexpr(order_3)
        {
            ++third_iterator;
            ++third_iterator_back;
        }
    }

    //!\brief Retreat the window of the iterators to their previous position.
    void retreat_windows()
    {
        --first_iterator;
        --second_iterator;
        --second_iterator_back;

        if constexpr(order_3)
        {
            --third_iterator;
            --third_iterator_back;
        }
    }

    //!\brief Calculates minstrobes for the first window.
    void window_first(const size_t window_dist, const size_t window_size)
    {
        if (window_size == 0u)
            return;

        urng_first = second_iterator;
        first_iterator = second_iterator;
        second_iterator_back = second_iterator;
        std::ranges::advance(second_iterator, window_dist);
        std::ranges::advance(second_iterator_back, window_dist);
        if constexpr(order_3)
        {
            third_iterator = second_iterator;
            third_iterator_back = second_iterator;
            std::ranges::advance(third_iterator, window_dist + window_size - 1);
            std::ranges::advance(third_iterator_back, window_dist + window_size - 1);
        }

        for (int i = 1u; i < window_size; ++i)
        {
            window_values.push_back(*second_iterator);
            ++second_iterator;

            if constexpr(order_3)
            {
                window_values3.push_back(*third_iterator);
                ++third_iterator;
            }
        }
        window_values.push_back(*second_iterator);

        auto minstrobe_it = std::ranges::min_element(window_values, std::less_equal<value_t>{});
        minstrobe_position_offset = std::distance(std::begin(window_values), minstrobe_it);

        if constexpr(order_3)
        {
            window_values3.push_back(*third_iterator);
            auto minstrobe_it3 = std::ranges::min_element(window_values3, std::less_equal<value_t>{});
            minstrobe_position_offset3 = std::distance(std::begin(window_values3), minstrobe_it3);
            minstrobe_value = {*first_iterator, *minstrobe_it, *minstrobe_it3};
        }
        else
        {
            minstrobe_value = {*first_iterator, *minstrobe_it};
        }
    }

    /*!\brief Calculates the next minstrobe value.
     * \details
     * For the following windows, we remove the first window value (is now not in window_values) and add the new
     * value that results from the window shifting.
     */
    void next_minstrobe()
    {
        advance_windows();

        if (second_iterator == urng_sentinel)
            return;
        value_t const new_value = *first_iterator;
        value_t const sw_new_value = *second_iterator;

        minstrobe_value[0]= new_value;

        window_values.pop_front();
        window_values.push_back(sw_new_value);
        if constexpr(order_3)
        {
            value_t const sw_new_value3 = *third_iterator;
            window_values3.pop_front();
            window_values3.push_back(sw_new_value3);

            if (sw_new_value3 < minstrobe_value[2])
            {
                minstrobe_value[2] = sw_new_value3;
                minstrobe_position_offset3 = window_values.size() - 1;
            }
            else if (minstrobe_position_offset3 == 0)
            {
                auto minstrobe_it3 = std::ranges::min_element(window_values3, std::less_equal<value_t>{});
                minstrobe_value[2] = *minstrobe_it3;
                minstrobe_position_offset3 = std::distance(std::begin(window_values3), minstrobe_it3);
            }
            else
            {
                --minstrobe_position_offset3;
            }
        }

        if (sw_new_value < minstrobe_value[1])
        {
            minstrobe_value[1] = sw_new_value;
            minstrobe_position_offset = window_values.size() - 1;
            return;
        }

        else if (minstrobe_position_offset == 0)
        {
            auto minstrobe_it = std::ranges::min_element(window_values, std::less_equal<value_t>{});
            minstrobe_value[1] = *minstrobe_it;
            minstrobe_position_offset = std::distance(std::begin(window_values), minstrobe_it);
            return;
        }

        --minstrobe_position_offset;
    }

    /*!\brief Calculates the previous minstrobe value.
     * \details
     * For the following windows, we remove the first window value (is now not in window_values) and add the new
     * value that results from the window shifting.
     */
    void prev_minstrobe()
        requires std::ranges::bidirectional_range<urng_t>
    {
        if (second_iterator_back == urng_first)
            return;
        if constexpr(order_3)
        {
            if (third_iterator_back == urng_first)
                return;
        }
        retreat_windows();

        value_t const new_value = *first_iterator;
        value_t const sw_new_value = *second_iterator_back;

        minstrobe_value[0]= new_value;

        window_values.pop_back();
        window_values.push_front(sw_new_value);

        if constexpr(order_3)
        {
            value_t const sw_new_value3 = *third_iterator_back;
            window_values3.pop_back();
            window_values3.push_front(sw_new_value3);

            if (sw_new_value3 < minstrobe_value[2])
            {
                minstrobe_value[2] = sw_new_value3;
                minstrobe_position_offset3 = 0;
            }
            else if (minstrobe_position_offset3 == window_values.size() - 1)
            {
                auto minstrobe_it3 = std::ranges::min_element(window_values3, std::less_equal<value_t>{});
                minstrobe_value[2] = *minstrobe_it3;
                minstrobe_position_offset3 = std::distance(std::begin(window_values3), minstrobe_it3);
            }
            else
            {
                ++minstrobe_position_offset3;
            }
        }

        if (sw_new_value < minstrobe_value[1])
        {
            minstrobe_value[1] = sw_new_value;
            minstrobe_position_offset = 0;
            return;
        }

        else if (minstrobe_position_offset == window_values.size() - 1)
        {
            auto minstrobe_it = std::ranges::min_element(window_values, std::less_equal<value_t>{});
            minstrobe_value[1] = *minstrobe_it;
            minstrobe_position_offset = std::distance(std::begin(window_values), minstrobe_it);
            return;
        }

        ++minstrobe_position_offset;
    }
};



//!\brief A deduction guide for the view class template.
template <std::ranges::viewable_range rng_t>
minstrobe_view(rng_t &&, size_t const window_dist, size_t const window_size) -> minstrobe_view<std::views::all_t<rng_t>>;

//!\brief A deduction guide for the view class template.
template <std::ranges::viewable_range rng_t, std::uint16_t ord>
minstrobe_view(rng_t &&, size_t const window_dist, size_t const window_size) -> minstrobe_view<std::views::all_t<rng_t>, ord>;


// ---------------------------------------------------------------------------------------------------------------------
// minstrobe_fn (adaptor definition)
// ---------------------------------------------------------------------------------------------------------------------

//![adaptor_def]
//!\brief minstrobe's range adaptor object type (non-closure).
//!\ingroup search_views
struct minstrobe_fn
{
    //!\brief Store the number of values in two windows and return a range adaptor closure object.
    constexpr auto operator()(const size_t window_dist, const size_t window_size) const
    {
        return adaptor_from_functor{*this, window_dist, window_size};
    }

    /*!\brief Call the view's constructor with three arguments: the underlying view and an integer indicating a lower
     *        offset and another integer indicating the upper offset of the second window.
     * \tparam urng_t         The type of the input range to process. Must model std::ranges::viewable_range.
     * \param[in] urange      The input range to process. Must model std::ranges::viewable_range and
     *                        std::ranges::forward_range.
     * \param[in] window_dist The distance of the second strobe to the first one.
     * \param[in] window_size The number of elements in a window.
     * \returns  A range of the converted values in vectors of size 2.
     */
    template <std::ranges::range urng_t>
    constexpr auto operator()(urng_t && urange, size_t const window_dist, size_t const window_size) const
    {
        static_assert(std::ranges::viewable_range<urng_t>,
                      "The range parameter to views::minstrobe cannot be a temporary of a non-view range.");
        static_assert(std::ranges::forward_range<urng_t>,
                      "The range parameter to views::minstrobe must model std::ranges::forward_range.");

        if (window_size <= window_dist)
            throw std::invalid_argument{"The chosen min and max windows are not valid."
                                        "Please choose a window_size greater than window_dist."};

        return minstrobe_view{urange, window_dist, window_size};
    }
};
//![adaptor_def]

} // namespace seqan3::detail

namespace seqan3::views
{
/*!\brief Computes minstrobes for a range of comparable values. A minstrobe consists of a starting strobe
 * concatenated with n−1 consecutively concatenated minimizers.
 * \tparam urng_t         The type of the range being processed. See below for requirements. [template
 *                        parameter is omitted in pipe notation]
 * \param[in] urange      The range being processed. [parameter is omitted in pipe notation]
 * \param[in] window_dist The distance of the second strobe to the first one.
 * \param[in] window_size The number of elements in a window.
 * \returns A range of std::totally_ordered where each value is a vector of size 2. See below for the
 *          properties of the returned range.
 * \ingroup search_views
 *
 * \details
 *
 * A minstrobe defined by [Sahlin](https://genome.cshlp.org/content/31/11/2080.full.pdf) consists of
 * a starting strobe concatenated with n−1 consecutively concatenated minimizers in their respective windows.
 * For example for the following list of hash values `[6, 26, 41, 38, 24, 33, 6, 27, 47]` and 3 as `window_dist`,
 * 4 as `window_size`, the minstrobe values are `[(6,24),(26,6),(41,6),(38,6)]`.
 *
 * ### View properties
 *
 * | Concepts and traits              | `urng_t` (underlying range type)   | `rrng_t` (returned range type)   |
 * |----------------------------------|:----------------------------------:|:--------------------------------:|
 * | std::ranges::input_range         | *required*                         | *preserved*                      |
 * | std::ranges::forward_range       | *required*                         | *preserved*                      |
 * | std::ranges::bidirectional_range |                                    | *preserved*                      |
 * | std::ranges::random_access_range |                                    | *lost*                           |
 * | std::ranges::contiguous_range    |                                    | *lost*                           |
 * |                                  |                                    |                                  |
 * | std::ranges::viewable_range      | *required*                         | *guaranteed*                     |
 * | std::ranges::view                |                                    | *guaranteed*                     |
 * | std::ranges::sized_range         |                                    | *lost*                           |
 * | std::ranges::common_range        |                                    | *lost*                           |
 * | std::ranges::output_range        |                                    | *lost*                           |
 * | seqan3::const_iterable_range     |                                    | *preserved*                      |
 * |                                  |                                    |                                  |
 * | std::ranges::range_reference_t   | std::totally_ordered               | std::totally_ordered             |
 *
 * See the views views submodule documentation for detailed descriptions of the view properties.
 */
inline constexpr auto minstrobe = detail::minstrobe_fn{};

} // namespace seqan3::views
