// -----------------------------------------------------------------------------------------------------
// Copyright (c) 2006-2021, Knut Reinert & Freie Universität Berlin
// Copyright (c) 2016-2021, Knut Reinert & MPI für molekulare Genetik
// This file may be used, modified and/or redistributed under the terms of the 3-clause BSD-License
// shipped with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE.md
// -----------------------------------------------------------------------------------------------------

/*!\file
 * \author Hossein Eizadi Moghadam <hosseinem AT fu-berlin.de>
 * \brief Provides syncmer.
 */

#pragma once

#include <seqan3/std/algorithm>
#include <deque>
#include <tuple>

#include <seqan3/core/detail/empty_type.hpp>
#include <seqan3/core/range/detail/adaptor_from_functor.hpp>
#include <seqan3/core/range/type_traits.hpp>
#include <seqan3/utility/range/concept.hpp>
#include <seqan3/utility/type_traits/lazy_conditional.hpp>

namespace seqan3::detail
{
// ---------------------------------------------------------------------------------------------------------------------
// syncmer_view class
// ---------------------------------------------------------------------------------------------------------------------

/*!\brief The type returned by syncmer.
 * \tparam urng1_t The type of the underlying range, must model std::ranges::forward_range, the reference type must
 *                 model std::totally_ordered. The typical use case is that the reference type is the result of
 *                 seqan3::kmer_hash.
 * \tparam measure_distance If true, then not the actual syncmers are returned, but the distances of the syncmers.
 * \implements std::ranges::view
 * \ingroup search_views
 *
 *
 * \note Most members of this class are generated by std::ranges::view_interface which is not yet documented here.

 */
template <std::ranges::view urng1_t>
class syncmer_view : public std::ranges::view_interface<syncmer_view<urng1_t>>
{
private:
    static_assert(std::ranges::forward_range<urng1_t>, "The syncmer_view only works on forward_ranges.");
    static_assert(std::totally_ordered<std::ranges::range_reference_t<urng1_t>>,
                  "The reference type of the underlying range must model std::totally_ordered.");

    //!\brief Whether the given ranges are const_iterable
    static constexpr bool const_iterable = seqan3::const_iterable_range<urng1_t>;

    //!\brief The first underlying range.
    urng1_t urange1{};
    size_t K{};
    size_t window_size{};
    size_t S{};
    //!\brief The number of values in one window.
    

    template <bool const_range>
    class basic_iterator;

    //!\brief The sentinel type of the syncmer_view.
    using sentinel = std::default_sentinel_t;

public:
    /*!\name Constructors, destructor and assignment
     * \{
     */
     /// \cond Workaround_Doxygen
    syncmer_view() requires std::default_initializable<urng1_t> = default; //!< Defaulted.
    /// \endcond
    syncmer_view(syncmer_view const & rhs) = default; //!< Defaulted.
    syncmer_view(syncmer_view && rhs) = default; //!< Defaulted.
    syncmer_view & operator=(syncmer_view const & rhs) = default; //!< Defaulted.
    syncmer_view & operator=(syncmer_view && rhs) = default; //!< Defaulted.
    ~syncmer_view() = default; //!< Defaulted.

    /*!\brief Construct from a view and a given number of values in one window.
    * \param[in] urange1     The input range to process. Must model std::ranges::viewable_range and
    *                        std::ranges::forward_range.
    * \param[in] mod_used The number of values in one window.
    */
    syncmer_view(urng1_t urange1, size_t const K, size_t const window_size, size_t const S) :
        urange1{std::move(urange1)},
        K{K},
        window_size{window_size},
        S{S}
    {}

    /*!\brief Construct from a non-view that can be view-wrapped and a given number of values in one window.
    * \tparam other_urng1_t  The type of another urange. Must model std::ranges::viewable_range and be constructible
                             from urng1_t.
    * \param[in] urange1     The input range to process. Must model std::ranges::viewable_range and
    *                        std::ranges::forward_range.
    * \param[in] mod_used The number of values in one window.
    */
    template <typename other_urng1_t>
    //!\cond
        requires (std::ranges::viewable_range<other_urng1_t> &&
                  std::constructible_from<urng1_t, ranges::ref_view<std::remove_reference_t<other_urng1_t>>>)
    //!\endcond
    syncmer_view(other_urng1_t && urange1, size_t const K, size_t const window_size, size_t const S) :
        urange1{std::views::all(std::forward<other_urng1_t>(urange1))},
        K{K},
        window_size{window_size},
        S{S}
    {}

    /*!\name Iterators
     * \{
     */
    /*!\brief Returns an iterator to the first element of the range.
     * \returns Iterator to the first element.
     *
     * \details
     *
     * ### Complexity
     *
     * Constant.
     *
     * ### Exceptions
     *
     * Strong exception guarantee.
     */
    basic_iterator<false> begin()
    {
        return {std::ranges::begin(urange1),
                std::ranges::end(urange1),
                K,
                window_size,
                S};
    }

    //!\copydoc begin()
    basic_iterator<true> begin() const
    //!\cond
        requires const_iterable
    //!\endcond
    {
        return {std::ranges::cbegin(urange1),
                std::ranges::cend(urange1),
                K,
                window_size,
                S};
    }

    /*!\brief Returns an iterator to the element following the last element of the range.
     * \returns Iterator to the end.
     *
     * \details
     *
     * This element acts as a placeholder; attempting to dereference it results in undefined behaviour.
     *
     * ### Complexity
     *
     * Constant.
     *
     * ### Exceptions
     *
     * No-throw guarantee.
     */
    sentinel end() const
    {
        return {};
    }
    //!\}
};

//!\brief Iterator for calculating syncmers.
template <std::ranges::view urng1_t>
template <bool const_range>
class syncmer_view<urng1_t>::basic_iterator
{
private:
    //!\brief The sentinel type of the first underlying range.
    using urng1_sentinel_t = maybe_const_sentinel_t<const_range, urng1_t>;
    //!\brief The iterator type of the first underlying range.
    using urng1_iterator_t = maybe_const_iterator_t<const_range, urng1_t>;

    template <bool>
    friend class basic_iterator;

public:
    /*!\name Associated types
     * \{
     */
    //!\brief Type for distances between iterators.
    using difference_type = std::ranges::range_difference_t<urng1_t>;
    //!\brief Value type of this iterator.
    using value_type = std::ranges::range_value_t<urng1_t>;
    //!\brief The pointer type.
    using pointer = void;
    //!\brief Reference to `value_type`.
    using reference = value_type;
    //!\brief Tag this class as a forward iterator.
    using iterator_category = std::forward_iterator_tag;
    //!\brief Tag this class as a forward iterator.
    using iterator_concept = iterator_category;
    //!\}

    /*!\name Constructors, destructor and assignment
     * \{
     */
    basic_iterator() = default; //!< Defaulted.
    basic_iterator(basic_iterator const &) = default; //!< Defaulted.
    basic_iterator(basic_iterator &&) = default; //!< Defaulted.
    basic_iterator & operator=(basic_iterator const &) = default; //!< Defaulted.
    basic_iterator & operator=(basic_iterator &&) = default; //!< Defaulted.
    ~basic_iterator() = default; //!< Defaulted.

    //!\brief Allow iterator on a const range to be constructible from an iterator over a non-const range.
    basic_iterator(basic_iterator<!const_range> const & it)
    //!\cond
        requires const_range
    //!\endcond
        : syncmer_value{std::move(it.syncmer_value)},
          urng1_iterator{std::move(it.urng1_iterator)},
          urng1_sentinel{std::move(it.urng1_sentinel)}
    {}

    /*!\brief Construct from begin and end iterators of a given range over std::totally_ordered values, and the number
              of values per window.
    * \param[in] urng1_iterator Iterator pointing to the first position of the first std::totally_ordered range.
    * \param[in] urng1_sentinel Iterator pointing to the last position of the first std::totally_ordered range.
    * \param[in] mod_used The number of values in one window.
    *
    * \details
    *
    * Looks at the number of values per window in two ranges, returns the smallest between both as syncmer and
    * shifts then by one to repeat this action. If a syncmer in consecutive windows is the same, it is returned only
    * once.
    */
    basic_iterator(urng1_iterator_t urng1_iterator,
                   urng1_sentinel_t urng1_sentinel,
                   size_t K,
                   size_t window_size,
                   size_t S) :
        urng1_iterator{std::move(urng1_iterator)},
        urng1_sentinel{std::move(urng1_sentinel)}
    {
        window_first(K, window_size, S);
    }
    //!\}

    //!\anchor basic_iterator_comparison_syncmer
    //!\name Comparison operators
    //!\{

    //!\brief Compare to another basic_iterator.
    friend bool operator==(basic_iterator const & lhs, basic_iterator const & rhs)
    {
        return (lhs.urng1_iterator == rhs.urng1_iterator);
    }

    //!\brief Compare to another basic_iterator.
    friend bool operator!=(basic_iterator const & lhs, basic_iterator const & rhs)
    {
        return !(lhs == rhs);
    }

    //!\brief Compare to the sentinel of the syncmer_view.
    friend bool operator==(basic_iterator const & lhs, sentinel const &)
    {
        return lhs.urng1_iterator == lhs.urng1_sentinel;
    }

    //!\brief Compare to the sentinel of the syncmer_view.
    friend bool operator==(sentinel const & lhs, basic_iterator const & rhs)
    {
        return rhs == lhs;
    }

    //!\brief Compare to the sentinel of the syncmer_view.
    friend bool operator!=(sentinel const & lhs, basic_iterator const & rhs)
    {
        return !(lhs == rhs);
    }

    //!\brief Compare to the sentinel of the syncmer_view.
    friend bool operator!=(basic_iterator const & lhs, sentinel const & rhs)
    {
        return !(lhs == rhs);
    }
    //!\}

    //!\brief Pre-increment.
    basic_iterator & operator++() noexcept
    {
        next_unique_syncmer();
        return *this;
    }

    //!\brief Post-increment.
    basic_iterator operator++(int) noexcept
    {
        basic_iterator tmp{*this};
        next_unique_syncmer();
        return tmp;
    }

    //!\brief Return the syncmer.
    value_type operator*() const noexcept
    {
        return syncmer_value;
    }

private:
    //!\brief The syncmer value.
    value_type syncmer_value{};

    //!\brief The offset relative to the beginning of the window where the minimizer value is found.
    size_t syncmer_position_offset{};

    //!\brief Iterator to the rightmost value of one window.
    urng1_iterator_t urng1_iterator{};
    urng1_iterator_t smallest_s_it{};
    //!brief Iterator to last element in range.
    urng1_sentinel_t urng1_sentinel{};
    //!\brief Iterator to the rightmost value of one window of the second range.


    //!\brief Stored values per window. It is necessary to store them, because a shift can remove the current syncmer.
    std::deque<value_type> window_values{};
    bool first;
    size_t POS{};
    size_t k{};
    size_t s{};
    size_t w_size{};
    //!\brief Increments iterator by 1.
    void next_unique_syncmer()
    {
        while (!next_syncmer()) {}
    }

    //!\brief Returns new window value.
    auto window_value() const
    {
        return *urng1_iterator;
    }
    

    //!\brief Advances the window to the next position.
    void advance_window()
    {
        ++urng1_iterator;
    }
    
    
    //!\brief Calculates syncmers for the first window.
    void window_first(size_t const K, size_t const window_size, size_t const S)
    {
        s=S;
	k=K;
	w_size = window_size;

	if (window_size == 0u)
            return;

        for (int i = 1u; i < ( window_size - (S - 1) ); ++i)
        {
            window_values.push_back(window_value());
            advance_window();
        }
        window_values.push_back(window_value());
	
        auto smallest_s_it = std::ranges::min_element(window_values, std::less_equal<value_type>{});
	syncmer_position_offset = std::distance(std::begin(window_values), smallest_s_it);

	if (K-(S-1)-1 <= syncmer_position_offset) {
		auto syncmer_it = smallest_s_it - (K - 1) + (S-1);
		syncmer_value = *syncmer_it;
		first = true;
	};

	if ( syncmer_position_offset + (S + k - 3) <= window_size ) {
		auto syncmer_it = smallest_s_it;
		syncmer_value = *syncmer_it;
	};	


        
	
    }

    /*!\brief Calculates the next syncmer value.
     * \returns True, if new syncmer is found or end is reached. Otherwise returns false.
     * \details
     * For the following windows, we remove the first window value (is now not in window_values) and add the new
     * value that results from the window shifting.
     */
    bool next_syncmer()
    {
    	//for (std::vector<value_type> vec : syncmers){
    	//	for (value_type i : vec){ std::cout << i << std::endl;};
    	//};
    	advance_window();

         
        if (urng1_iterator == urng1_sentinel)
            return true;

        value_type const new_value = window_value();
        
        window_values.pop_front();
        window_values.push_back(new_value);

	if (syncmer_position_offset == 0)
	{
		auto smallest_s_it = std::ranges::min_element(window_values, std::less_equal<value_type>{});
		syncmer_position_offset = std::distance(std::begin(window_values), smallest_s_it);

		if (k-(s-1)-1 <= syncmer_position_offset) {

			auto syncmer_it = smallest_s_it - (k - 1) + (s-1);
			syncmer_value = *syncmer_it;
			first = true;
		};

		if ( syncmer_position_offset + (s + k - 3) <= w_size ) {
			auto syncmer_it = smallest_s_it;
			syncmer_value = *syncmer_it;
		};

		return true;
	}
	
	if (new_value < *(window_values.begin()+syncmer_position_offset-1) && syncmer_position_offset != window_values.size() - k + s )
	     {
									
	          syncmer_position_offset = window_values.size() - 1;
		  auto syncmer_it = urng1_iterator - (k - 1) + (s-1);
		  syncmer_value = *syncmer_it;
	          return true;
	     }

	if ( syncmer_position_offset - 1 + (s + k - 3) <= w_size && first) {

		auto syncmer_it = (window_values.begin()+syncmer_position_offset - 1);
		syncmer_value = *syncmer_it;
		--syncmer_position_offset;
		first = false;
		return true;
	};

		
	 
	--syncmer_position_offset;
	return false;
    }
};



//!\brief A deduction guide for the view class template.
template <std::ranges::viewable_range rng1_t>
syncmer_view(rng1_t &&, size_t const K, size_t const window_size, size_t const S) -> syncmer_view<std::views::all_t<rng1_t>>;



// ---------------------------------------------------------------------------------------------------------------------
// syncmer_fn (adaptor definition)
// ---------------------------------------------------------------------------------------------------------------------

//![adaptor_def]
//!\brief syncmer's range adaptor object type (non-closure).
//!\ingroup search_views
struct syncmer_fn
{
    //!\brief Store the number of values in one window and return a range adaptor closure object.
    constexpr auto operator()(const size_t K, const size_t window_size, const size_t S) const
    {
        return adaptor_from_functor{*this, K, window_size, S};
    }

    /*!\brief Call the view's constructor with two arguments: the underlying view and an integer indicating how many
     *        values one window contains.
     * \tparam urng1_t        The type of the input range to process. Must model std::ranges::viewable_range.
     * \param[in] urange1     The input range to process. Must model std::ranges::viewable_range and
     *                        std::ranges::forward_range.
     * \param[in] mod_used The number of values in one window.
     * \returns  A range of converted values.
     */
    template <std::ranges::range urng1_t>
    constexpr auto operator()(urng1_t && urange1, size_t const K, size_t const window_size, size_t const S) const
    {
        static_assert(std::ranges::viewable_range<urng1_t>,
                      "The range parameter to views::syncmer cannot be a temporary of a non-view range.");
        static_assert(std::ranges::forward_range<urng1_t>,
                      "The range parameter to views::syncmer must model std::ranges::forward_range.");

        if (window_size - K == -1) // Would just return urange1 without any changes
            throw std::invalid_argument{"The chosen K-mer and window size are not valid. "
                                        "Please choose a value that satisfize the given condition."};

        return syncmer_view{urange1, K, window_size, S};
    }
};
//![adaptor_def]

} // namespace seqan3::detail

namespace seqan3::views
{
/*!\brief Computes syncmers for a range of comparable values. A syncmer is a value that fullfills the
          condition value % mod_used.
 * \tparam urng_t The type of the first range being processed. See below for requirements. [template
 *                 parameter is omitted in pipe notation]
 * \param[in] urange1 The range being processed. [parameter is omitted in pipe notation]
 * \param[in] mod_used The mod value used.
 * \returns A range of std::totally_ordered where each value is ... See below for the
 *          properties of the returned range.
 * \ingroup search_views
 *
 *
 * ### View properties
 *
 * | Concepts and traits              | `urng_t` (underlying range type)   | `rrng_t` (returned range type)   |
 * |----------------------------------|:----------------------------------:|:--------------------------------:|
 * | std::ranges::input_range         | *required*                         | *preserved*                      |
 * | std::ranges::forward_range       | *required*                         | *preserved*                      |
 * | std::ranges::bidirectional_range |                                    | *lost*                           |
 * | std::ranges::random_access_range |                                    | *lost*                           |
 * | std::ranges::contiguous_range    |                                    | *lost*                           |
 * |                                  |                                    |                                  |
 * | std::ranges::viewable_range      | *required*                         | *guaranteed*                     |
 * | std::ranges::view                |                                    | *guaranteed*                     |
 * | std::ranges::sized_range         |                                    | *lost*                           |
 * | std::ranges::common_range        |                                    | *lost*                           |
 * | std::ranges::output_range        |                                    | *lost*                           |
 * | seqan3::const_iterable_range     |                                    | *preserved*                      |
 * |                                  |                                    |                                  |
 * | std::ranges::range_reference_t   | std::totally_ordered               | std::totally_ordered             |
 *
 * See the views views submodule documentation for detailed descriptions of the view properties.
 */
inline constexpr auto syncmer = detail::syncmer_fn{};

} // namespace seqan3::views
