rule all:
    input:
        "0_Human_kmer_hash_16_counts.out",
        "36607_Human_kmer_hash_16_counts.out",
        "51755_Human_kmer_hash_16_counts.out",
        "0_Human_kmer_hash_20_counts.out",
        "933855_Human_kmer_hash_20_counts.out",
        "975475_Human_kmer_hash_20_counts.out",
        "0_Human_kmer_hash_24_counts.out",
        "14548847_Human_kmer_hash_24_counts.out",
        "13954519_Human_kmer_hash_24_counts.out",
        "0_Human_kmer_hash_28_counts.out",
        "192920575_Human_kmer_hash_28_counts.out",
        "241004285_Human_kmer_hash_28_counts.out",
        "0_Human_kmer_hash_32_counts.out",
        "3758077695_Human_kmer_hash_32_counts.out",
        "3169577727_Human_kmer_hash_32_counts.out",
        "0_Mouse_kmer_hash_16_counts.out",
        "36607_Mouse_kmer_hash_16_counts.out",
        "51755_Mouse_kmer_hash_16_counts.out",
        "0_Mouse_kmer_hash_20_counts.out",
        "933855_Mouse_kmer_hash_20_counts.out",
        "975475_Mouse_kmer_hash_20_counts.out",
        "0_Mouse_kmer_hash_24_counts.out",
        "14548847_Mouse_kmer_hash_24_counts.out",
        "13954519_Mouse_kmer_hash_24_counts.out",
        "0_Mouse_kmer_hash_28_counts.out",
        "192920575_Mouse_kmer_hash_28_counts.out",
        "241004285_Mouse_kmer_hash_28_counts.out",
        "0_Mouse_kmer_hash_32_counts.out",
        "3758077695_Mouse_kmer_hash_32_counts.out",
        "3169577727_Mouse_kmer_hash_32_counts.out",
        "0_Wheat_kmer_hash_16_counts.out",
        "36607_Wheat_kmer_hash_16_counts.out",
        "51755_Wheat_kmer_hash_16_counts.out",
        "0_Wheat_kmer_hash_20_counts.out",
        "933855_Wheat_kmer_hash_20_counts.out",
        "975475_Wheat_kmer_hash_20_counts.out",
        "0_Wheat_kmer_hash_24_counts.out",
        "14548847_Wheat_kmer_hash_24_counts.out",
        "13954519_Wheat_kmer_hash_24_counts.out",
        "0_Wheat_kmer_hash_28_counts.out",
        "192920575_Wheat_kmer_hash_28_counts.out",
        "241004285_Wheat_kmer_hash_28_counts.out",
        "0_Wheat_kmer_hash_32_counts.out",
        "3758077695_Wheat_kmer_hash_32_counts.out",
        "3169577727_Wheat_kmer_hash_32_counts.out"

rule download_human_genome:
    output:
        "GRCh38.p13.genome.fa.gz"
    shell:
        """wget "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/GRCh38.p13.genome.fa.gz" """

rule download_mouse_genome:
    output:
        "Mus_musculus.GRCm39.dna.primary_assembly.fa.gz"
    shell:
        """wget "http://ftp.ensembl.org/pub/release-106/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz" """

rule download_wheat_genome:
    output:
        "Triticum_aestivum.IWGSC.dna.toplevel.fa.gz"
    shell:
        """wget "http://ftp.ensemblgenomes.org/pub/plants/release-53/fasta/triticum_aestivum/dna/Triticum_aestivum.IWGSC.dna.toplevel.fa.gz" """


rule count_human:
    input:
        "GRCh38.p13.genome.fa.gz"
    output:
        "{shape}_Human_kmer_hash_{kmer_size}_counts.out"
    shell:
        "minions counts --method kmer -k {wildcards.kmer_size} --shape {wildcards.shape} -o {wildcards.shape}_Human_ {input}"

rule count_mouse:
    input:
        "Mus_musculus.GRCm39.dna.primary_assembly.fa.gz"
    output:
        "{shape}_Mouse_kmer_hash_{kmer_size}_counts.out"
    shell:
        "minions counts --method kmer -k {wildcards.kmer_size} --shape {wildcards.shape} -o {wildcards.shape}_Mouse_ {input}"

rule count_wheat:
    input:
        "Triticum_aestivum.IWGSC.dna.toplevel.fa.gz"
    output:
        "{shape}_Wheat_kmer_hash_{kmer_size}_counts.out"
    shell:
        "minions counts --method kmer -k {wildcards.kmer_size} --shape {wildcards.shape} -o {wildcards.shape}_Wheat_ {input}"
